name: CI

on:
  push:

jobs:
  setup-build-matrix:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    runs-on: ubuntu-18.04
    steps:
      - name: Build matrix
        id: build-matrix
        uses: jgiannuzzi/setup-build-matrix@v1
        with:
          config: |
            matrix:
              os: [ubuntu-18.04, ubuntu-20.04, windows-2016, windows-2019, macos-10.15, macos-11.0]
              component: [Consul, Consul.AspNetCore]
              dotnet: [3.1.405, 5.0.102]
            operations:
              - type: merge
                match: [component]
                matrix:
                  component: [Consul]
                  consul: [1.6.10, 1.7.11, 1.8.7, 1.9.2]
              - type: add
                match: [component]
                matrix:
                  component: [Consul]
                  dotnet: [2.1.812]
              - type: add
                match: [os, component]
                matrix:
                  os: [windows-2016, windows-2019]
                  component: [Consul]
                  dotnet: ["4.7"]
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}

  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    needs: setup-build-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-build-matrix.outputs.matrix) }}
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Debug
        shell: bash
        run: |
          echo "os: ${{ matrix.os }}"
          echo "component: ${{ matrix.component }}"
          echo "consul: ${{ matrix.consul }}"
          echo "dotnet: ${{ matrix.dotnet }}"
